=== MAXBURAOT/jenova-project/TeraGame/data/schema/player_basestats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/player_basestats"
    xmlns:xsd="http://angelis.com/player_basestats" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    
    <!-- IMPORT -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base"/>
    
    <complexType name="PlayerBaseStatType">
        <sequence>
            <element name="basestat" type="base:BaseStatType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="targetClass" type="base:ClassType"/>
    </complexType>
    <complexType name="PlayerBaseStatsType">
        <sequence>
            <element name="player_basestat" type="xsd:PlayerBaseStatType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- CONTENT -->
    <element name="player_basestats" type="xsd:PlayerBaseStatsType"/>
</schema>

=== MAXBURAOT/jenova-project/TeraGame/data/xml/player_basestats.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_basestats xmlns="http://angelis.com/player_basestats" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/player_basestats ../schema/player_basestats.xsd "
>
    <player_basestat targetClass="WARRIOR">
        <basestat level="1" base_hp="1544" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="10" combat_hp_regen="10" combat_mp_regen="10"/>
        <basestat level="2" base_hp="1632" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="10" combat_hp_regen="10" combat_mp_regen="10"/>
        <basestat level="3" base_hp="1725" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="10" combat_mp_regen="13"/>
        <basestat level="4" base_hp="1824" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="11" combat_mp_regen="13"/>
        <basestat level="5" base_hp="1927" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="11" combat_mp_regen="13"/>
        <basestat level="6" base_hp="2037" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="13" combat_mp_regen="13"/>
        <basestat level="7" base_hp="2152" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="13" combat_mp_regen="13"/>
        <basestat level="8" base_hp="2273" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="14" combat_mp_regen="13"/>
        <basestat level="9" base_hp="2402" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="15" combat_mp_regen="13"/>
        <basestat level="10" base_hp="2537" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="75" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="16" combat_mp_regen="13"/>
    </player_basestat>
    
    <player_basestat targetClass="LANCER">
        <!-- TODO -->
        <basestat level="1" base_hp="1544" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="10" combat_hp_regen="10" combat_mp_regen="10"/>
        <basestat level="2" base_hp="1632" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="10" combat_hp_regen="10" combat_mp_regen="10"/>
        <basestat level="3" base_hp="1725" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="10" combat_mp_regen="13"/>
        <basestat level="4" base_hp="1824" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="11" combat_mp_regen="13"/>
        <basestat level="5" base_hp="1927" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="11" combat_mp_regen="13"/>
        <basestat level="6" base_hp="2037" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="13" combat_mp_regen="13"/>
        <basestat level="7" base_hp="2152" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="13" combat_mp_regen="13"/>
        <basestat level="8" base_hp="2273" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="14" combat_mp_regen="13"/>
        <basestat level="9" base_hp="2402" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="15" combat_mp_regen="13"/>
        <basestat level="10" base_hp="2537" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="75" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="16" combat_mp_regen="13"/>
    </player_basestat>
    
    <player_basestat targetClass="SLAYER">
        <!-- TODO -->
        <basestat level="1" base_hp="1544" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="10" combat_hp_regen="10" combat_mp_regen="10"/>
        <basestat level="2" base_hp="1632" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="10" combat_hp_regen="10" combat_mp_regen="10"/>
        <basestat level="3" base_hp="1725" base_mp="1000" attack="4" defense="2" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="46" endurance="78" impact_factor="40" balance_factor="60" attack_speed="120" speed="120" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="0" natural_mp_degen="13" combat_hp_regen="10" combat_mp_regen="13"/>
